ADS/urls.py
from django.contrib import admin
from django.urls import include, path, re_path

from list_of_request.views import page_not_found
from ATS.views import CallViewSet
from rest_framework.routers import DefaultRouter


router = DefaultRouter()
router.register(r'calls', CallViewSet)
from django.conf import settings
from django.conf.urls.static import static




urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main.urls', namespace='main')),
    path('list_of_request/', include('list_of_request.urls', namespace='list_of_request')),
    path('user/', include('users.urls', namespace='users')),
    path('handbook/', include('handbook.urls', namespace='handbook')),
    path('company/', include('companies.urls', namespace='company')),
    path('calls/', include('ATS.urls', namespace='ATS')),
    path('api/v1/drf-auth/', include('rest_framework.urls')),
    path('sms/', include('sms_app.urls', namespace='sms')),
    path('api/v1/auth/', include('djoser.urls')),
    # path('bot/', include('bot.urls')),
    re_path(r'^auth/', include('djoser.urls.authtoken')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
urlpatterns += router.urls


handler404 = page_not_found

companies/urls.py
from django.urls import path
from companies import views

app_name = 'companies'

urlpatterns = [
    path('', views.company, name='company'),
    path('create_company/', views.create_company, name='create_company'),
    path('show/<slug:company_id>/', views.CompanyDetail.as_view(), name='show_company'),
]

handbook/urls.py
from django.urls import path
from handbook import views


app_name = 'handbook'

urlpatterns = [
    path('', views.handbook, name='handbook'),
    path('city/', views.city, name='city'),
    path('street/', views.street, name='street'),
    path('create_street/', views.create_street, name='create_street'),
    path('house/', views.house, name='house'),
    path('create_house/', views.create_house, name='create_house'),
    path('type_application/', views.type_application, name='type_application'),
    path('view_application/', views.view_application, name='view_application'),
    path('status_application/', views.status_application, name='status_application'),
    path('executors/', views.executor, name='executor'),
    # path('executors/add', views.executor_add, name='add_executor'),
    path('masters/', views.master, name='master'),
    path('masters/add', views.master_add, name='add_master'),
]

handbook/forms.py
from django import forms
from django.forms import ModelForm

from companies.models import Cities, Companies, Master, PublishedManager, Worker
from .models import House, Street, Roles
from django.contrib.auth.models import User


class MasterForm(forms.ModelForm):
    name = forms.TextInput()
    
    
class WorkerForm(forms.ModelForm):
    name = forms.TextInput()
    
    
class Dezh_WorkerForm(forms.ModelForm):
    name = forms.TextInput()
    
    
class WorkersForm(forms.ModelForm):
    worker = forms.ModelChoiceField(queryset=Worker.published.all(), empty_label="Исполнитель не выбран", required=False, label="Исполнитель")
    master = forms.ModelChoiceField(queryset=Master.published.all(), empty_label="Мастер не выбран", required=False, label="Мастер")
    
                    


# class CityForm(forms.ModelForm):
#     name = forms.TextInput()
#     status = forms.BooleanField()

    

class StreetForm(forms.ModelForm):
    name = forms.TextInput()
    city = forms.ModelChoiceField(queryset=Cities.objects.all(), empty_label="Город не выбран", required=False, label="Город")
    status = forms.BooleanField()

    class Meta:
        model = Street
        fields = ['name', 'city', 'status']
        widgets = {
            "name": forms.TextInput(attrs={
                'class': 'form-control',
                'placeholder': 'Название'
            }),
            "city": forms.TextInput(attrs={
                'class': 'form-control',
                'placeholder': 'Город'
            })
        }
        
class AddMasterForm(forms.ModelForm):
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['name'].empty_label = 'Введите имя'
        self.fields['phone_number'].empty_label = 'Введите номер телефона'
        # self.fields['company'].empty_label = 'Введите номер телефона'
        self.fields['user'].empty_label = 'Выберите аккаунт'
    
    class Meta:
        model = Worker
        fields = ['name', 'phone_number', 'user'] 
        widgets = {
            "name": forms.TextInput(attrs={
                'class': 'form-control',
                'placeholder': 'Имя мастера'
            }),
            "phone_number": forms.TextInput(attrs={
                'class': 'form-control',
                'placeholder': 'Номер телефона'
            }),
            # "company": forms.Select(attrs={
            #     'class': 'form-control'                
            # }),
            "user": forms.Select(attrs={
                'class': 'form-control'
            })
        }
        def clean(self):
            cleaned_data = super().clean()
            return cleaned_data
        

    
# class AddWorkerForm(forms.ModelForm):
#     def __init__(self, *args, **kwargs):
#         super().__init__(*args, **kwargs)
#         self.fields['name'].empty_label = 'Введите имя'
#         self.fields['type_worker'].empty_label = 'Выберите тип заявок'
#         # self.fields['sms'].empty_label = 'Выберите статус смс'
#         self.fields['phone_number'].empty_label = 'Введите номер телефона'
#         # self.fields['company'].empty_label = 'Выберите компанию'
#         self.fields['user'].empty_label = 'Выберите аккаунт исполнителя'
        
#     class Meta:
#         model = Worker
#         fields = ['name', 'type_worker', 'phone_number', 'user'] 
#         widgets = {
#             "name": forms.TextInput(attrs={
#                 'class': 'form-control',
#                 'placeholder': 'Имя работника'
#             }),
#             "type_worker": forms.Select(attrs={
#                 'class': 'form-control'
#             }),
#             "phone_number": forms.TextInput(attrs={
#                 'class': 'form-control',
#                 'placeholder': 'Номер телефона'
#             }),
#             # "company": forms.Select(attrs={
#             #     'class': 'form-control'
#             # }),
#             # "sms": forms.BooleanField(attrs={
#             #     'class': 'form-control'
#             # }),
#             "user": forms.Select(attrs={
#                 'class': 'form-control'
#             })
#         }
#         def clean(self):
#             cleaned_data = super().clean()
#             return cleaned_data
        
class HouseForm(forms.ModelForm):
    name = forms.TextInput()
    street = forms.ModelChoiceField(queryset=Street.objects.all(), empty_label="Улица не выбрана", required=False, label="Улица")
    company = forms.ModelChoiceField(queryset=Companies.published.all(), empty_label="Компания не выбрана", required=False, label="Компания")
    master = forms.ModelChoiceField(queryset=Master.published.all(), empty_label="Мастер не выбран", required=False, label="Мастер")
    status = forms.BooleanField()
    plumbing = forms.ModelChoiceField(queryset=Worker.published.all(), empty_label="Сантехник не выбран", required=False, label="Сантехник")
    electrician = forms.ModelChoiceField(queryset=Worker.published.all(), empty_label="Электрик не выбран", required=False, label="Электрик")
    carpenter = forms.ModelChoiceField(queryset=Worker.published.all(), empty_label="Исполнитель не выбран", required=False, label="Исполнитель")
    cleaners = forms.ModelChoiceField(queryset=Worker.published.all(), empty_label="Исполнитель не выбран", required=False, label="Исполнитель")
    wipers = forms.ModelChoiceField(queryset=Worker.published.all(), empty_label="Исполнитель не выбран", required=False, label="Исполнитель")
    improvement = forms.ModelChoiceField(queryset=Worker.published.all(), empty_label="Исполнитель не выбран", required=False, label="Исполнитель")
    plumber_certificate = forms.ModelChoiceField(queryset=Worker.published.all(), empty_label="Исполнитель не выбран", required=False, label="Исполнитель")
    electrician_certificate = forms.ModelChoiceField(queryset=Worker.published.all(), empty_label="Исполнитель не выбран", required=False, label="Исполнитель")
    networks = forms.ModelChoiceField(queryset=Worker.published.all(), empty_label="Исполнитель не выбран", required=False, label="Исполнитель")
    act = forms.ModelChoiceField(queryset=Worker.published.all(), empty_label="Исполнитель не выбран", required=False, label="Исполнитель")
    deratization = forms.ModelChoiceField(queryset=Worker.published.all(), empty_label="Исполнитель не выбран", required=False, label="Исполнитель")
    pest_control = forms.ModelChoiceField(queryset=Worker.published.all(), empty_label="Исполнитель не выбран", required=False, label="Исполнитель")
    disinfection = forms.ModelChoiceField(queryset=Worker.published.all(), empty_label="Исполнитель не выбран", required=False, label="Исполнитель")
    verification_of_meters = forms.ModelChoiceField(queryset=Worker.published.all(), empty_label="Исполнитель не выбран", required=False, label="Исполнитель")
    SOI_inspection = forms.ModelChoiceField(queryset=Worker.published.all(), empty_label="Исполнитель не выбран", required=False, label="Исполнитель")
    passport = forms.ModelChoiceField(queryset=Worker.published.all(), empty_label="Исполнитель не выбран", required=False, label="Исполнитель")
    intercom_ROST = forms.ModelChoiceField(queryset=Worker.published.all(), empty_label="Исполнитель не выбран", required=False, label="Исполнитель")
    
    
    class Meta:
        model = House
        fields = ['name', 'street', 'company',]
        # widgets = {
        #     "name": forms.TextInput(attrs={
        #         'class': 'form-control',
        #         'placeholder': 'Название'
        #     }),
        #     "city": forms.TextInput(attrs={
        #         'class': 'form-control',
        #         'placeholder': 'Город'
        #     }),
        #     "status": forms.BooleanField(attrs={
        #         'class': 'form-control',
        #         'placeholder': 'Статус'
        #     }),
        #     "name": forms.TextInput(attrs={
        #         'class': 'form-control',
        #         'placeholder': 'Название'
        #     }),
        #     "city": forms.TextInput(attrs={
        #         'class': 'form-control',
        #         'placeholder': 'Город'
        #     }),
        #     "status": forms.BooleanField(attrs={
        #         'class': 'form-control',
        #         'placeholder': 'Статус'
        #     }),
        #     "name": forms.TextInput(attrs={
        #         'class': 'form-control',
        #         'placeholder': 'Название'
        #     }),
        #     "city": forms.TextInput(attrs={
        #         'class': 'form-control',
        #         'placeholder': 'Город'
        #     }),
        #     "status": forms.BooleanField(attrs={
        #         'class': 'form-control',
        #         'placeholder': 'Статус'
        #     }),
        #     "name": forms.TextInput(attrs={
        #         'class': 'form-control',
        #         'placeholder': 'Название'
        #     }),
        #     "city": forms.TextInput(attrs={
        #         'class': 'form-control',
        #         'placeholder': 'Город'
        #     }),
        #     "status": forms.BooleanField(attrs={
        #         'class': 'form-control',
        #         'placeholder': 'Статус'
        #     }),
        #     "name": forms.TextInput(attrs={
        #         'class': 'form-control',
        #         'placeholder': 'Название'
        #     }),
        #     "city": forms.TextInput(attrs={
        #         'class': 'form-control',
        #         'placeholder': 'Город'
        #     }),
        #     "status": forms.BooleanField(attrs={
        #         'class': 'form-control',
        #         'placeholder': 'Статус'
        #     }),
        #     "name": forms.TextInput(attrs={
        #         'class': 'form-control',
        #         'placeholder': 'Название'
        #     }),
        #     "city": forms.TextInput(attrs={
        #         'class': 'form-control',
        #         'placeholder': 'Город'
        #     }),

handbook/views.py
from django.http import HttpResponseRedirect
from django.shortcuts import render
from django.urls import reverse
from django.contrib import messages
from django.contrib.auth.decorators import login_required

from companies.models import Cities, Companies, Master, Worker

from .forms import AddMasterForm, HouseForm, StreetForm

from .models import  House, Status_application, Street, Type_application, View_application



@login_required 
def handbook(request):
    context = {
        "title": "Справочник",
    }
    return render(request, 'handbook/handbook.html', context)




@login_required 
def city(request):
    content = Cities.objects.all()
    context = {
        "title": "Города",
        "content": content,
    }
    return render(request, 'handbook/city.html', context)



@login_required 
def street(request):
    content = Street.objects.all()
    context = {
        "title": "Улицы",
        "content": content,
    }
    return render(request, 'handbook/street.html', context)

@login_required 
def create_street(request):
    error = ''
    if request.method=="POST":
        form = StreetForm(request.POST)
        if form.is_valid():
            new_app = form.save(commit=False)
            new_app.created_by = request.user
            
            new_app.save()
            return HttpResponseRedirect(reverse('handbook:street'))
        else:
            error = 'Форма была не верной'
    
    form = StreetForm()
    
    data = {
        'form': form,
        'error': error
    }
    
    return render(request, 'handbook/create_street.html', data)

@login_required 
def house(request):
    content = House.objects.filter(created_by=request.user)
    context = {
        "title": "Дома",
        "content": content,
    }
    return render(request, 'handbook/house.html', context)

@login_required 
def create_house(request):
    error = ''
    if request.method=="POST":
        form = HouseForm(request.POST)
        if form.is_valid():
            new_app = form.save(commit=False)
            new_app.created_by = request.user
            
            new_app.save()
            return HttpResponseRedirect(reverse('handbook:house'))
        else:
            error = 'Форма была не верной'
    
    form = HouseForm()
    
    data = {
        'form': form,
        'error': error
    }
    
    return render(request, 'handbook/create_house.html', data)



@login_required 
def type_application(request):
    content = Type_application.objects.all()
    context = {
        "title": "Тип заявки",
        "content": content,
    }
    return render(request, 'handbook/type_application.html', context)



@login_required 
def view_application(request):
    content = View_application.objects.all()
    context = {
        "title": "Вид заявки",
        "content": content,
    }
    return render(request, 'handbook/view_application.html', context)



@login_required 
def status_application(request):
    content = Status_application.objects.all()
    context = {
        "title": "Статус заявки",
        "content": content,
    }
    return render(request, 'handbook/status_application.html', context)



@login_required 
def executor(request):
    content = Worker.published.all()
    context = {
        "title": "Исполнители",
        "content": content,
    }
    return render(request, 'handbook/executor.html', context)

# def executor_add(request):
#     if request.method == 'POST':
#         form = AddWorkerForm(request.POST)
        
#         if form.is_valid():
#             company = Companies.objects.filter(created_by=request.user)[0]
#             executor = form.save(commit=False)
#             executor.user = request.user
#             executor.company = company
#             executor.save()
            
#             messages.success(request, 'Исполнитель успешно добавлен.')
            
#             return HttpResponseRedirect(reverse('handbook:executor'))
#     else:
#         form = AddWorkerForm()
            
#     return render(request, 'handbook/worker_add.html', {
#         'form': form})
@login_required 
def master(request):
    content = Master.published.all()
    context = {
        "title": "Мастера",
        "content": content,
        
        
    }
    return render(request, 'handbook/master.html', context)

@login_required 
def master_add(request):
    if request.method == 'POST':
        form = AddMasterForm(request.POST)
        
        if form.is_valid():
            company = Companies.objects.filter(created_by=request.user)[0]
            workers = Worker.objects.filter(user=request.user)[0]
            master = form.save(commit=False)
            master.user = request.user
            master.company = company
            master.workers = workers
            master.save()
            
            messages.success(request, 'Мастер успешно добавлен.')
            
            return HttpResponseRedirect(reverse('handbook:add_master'))
    else:
        form = AddMasterForm()
            
    return render(request, 'handbook/master_add.html', {
        'form': form})
    
            

handbook/templates/handbook/city.html
{% extends "handbook/handbook.html" %}
{%load static %}

{% block css %}
    <link rel="stylesheet" href="{% static "deps/css/my_footer_css.css" %}">
	<link rel="stylesheet" href="{% static "deps/css/table.css" %}">
{% endblock  %}

{% block content %}
<li><a class="dropdown-item text-black" href="#">Добавить город</a></li>

{% csrf_token %}
<h5 class="m-2"><strong>{{ title }}</strong></h5>
	<ul>
		<table class="table table-bordered" data-resizable-columns-id="demo-table">
			<tr>
				<th data-resizable-column-id="Название">Название</th>
				<th data-resizable-column-id="Действия">Действия</th>
            </tr>
			<tr>	
            {% for c in content %}
                
					<div class="mt-6 flex justify-content-between">
                        
						<td><p class="py-2 px-2 w-full {% cycle 'bg-gray-100' '' %}">{{ c.name }}</a></p></td>
						<td><p class="py-2 px-2 w-full {% cycle 'bg-gray-100' '' %}">{{ c.do }}</a></p></td>
					</div>
			</tr>
				{% endfor %}
		</table>

    </ul>

{% endblock  %}



{% comment %} {% block footer %}
<footer class="py-4 bg-dark">
    <div class="container">
        <p class="m-0 text-center text-white">Copyright &copy; Аварийно-диспечерская служба 2024</p>
    </div>
</footer>
{% endblock  %} {% endcomment %}

handbook/templates/handbook/create_company.html
{% extends "base.html" %}
{% load crispy_forms_tags %}
{%load static %}

{% block css %}
    <link rel="stylesheet" href="{% static "deps/css/my_footer_css.css" %}">
    <link rel="stylesheet" href="{% static "deps/css/form.css" %}">
{% endblock  %}

{% block content %}
    <div class="features">
        <h1>Создать новую компанию</h1>
        <form method="post">
            {% csrf_token %}
            {% crispy form %}
            
            <span>{{ error }}</span>
            <button class="btn btn-info"><i class="fas fa-plus-circle">Создать</button>
            </form>
            
        </div>
        
        {% endblock  %}
        
        
        
        {% block footer %}
        {% comment %} <footer class="py-4 bg-dark">
            <div class="container">
                <p class="m-0 text-center text-white">Copyright &copy; РђРІР°СЂРёР№РЅРѕ-РґРёСЃРїРµС‡РµСЂСЃРєР°СЏ СЃР»СѓР¶Р±Р° 2024</p>
                </div>
                </footer>  {% endcomment %}
                {% endblock  %}
                
                {% comment %} {{ form.name }}<br>
                {{ form.city }}<br>
                {{ form.phone_number }}<br><br>
                {{ form.mail }}<br> 
                {{ form.info }}<br>
                {{ form.sms_master }}<br>
                {{ form.sms_worker }}<br><br>
                {{ form.status }}<br> {% endcomment %}

handbook/templates/handbook/create_street.html
{% extends "base.html" %}

{%load static %}

{% block css %}
    <link rel="stylesheet" href="{% static "deps/css/my_footer_css.css" %}">
    <link rel="stylesheet" href="{% static "deps/css/form.css" %}">
{% endblock  %}

{% block content %}
    <div class="features">
        <h1>Добавить новую улицу</h1>
        <form method="post">
            {% csrf_token %}
            {{ form.name }}<br>
            {{ form.city }}<br>
            {{ form.status }}<br><br>
            
            <span>{{ error }}</span>
            <button class="btn btn-info"><i class="fas fa-plus-circle">Создать</button>
        </form>
        
    </div>
    
{% endblock  %}



{% block footer %}
{% comment %} <footer class="py-4 bg-dark">
    <div class="container">
        <p class="m-0 text-center text-white">Copyright &copy; РђРІР°СЂРёР№РЅРѕ-РґРёСЃРїРµС‡РµСЂСЃРєР°СЏ СЃР»СѓР¶Р±Р° 2024</p>
    </div>
</footer>  {% endcomment %}
{% endblock  %}

handbook/templates/handbook/executor.html
{% extends "handbook/handbook.html" %}
{%load static %}

{% block css %}
    <link rel="stylesheet" href="{% static "deps/css/my_footer_css.css" %}">
	<link rel="stylesheet" href="{% static "deps/css/table.css" %}">
{% endblock  %}

{% block content %}
{% csrf_token %}
<h5 class="m-2"><strong>{{ title }}</strong></h5>
	<ul>
		<table class="table table-bordered" data-resizable-columns-id="demo-table">
			<tr>
				<th data-resizable-column-id="Имя исполнителя">Имя исполнителятель</th>
                <th data-resizable-column-id="Тип заявок">Тип заявокель</th>
				<th data-resizable-column-id="Номер телефона">Номер телефона</th>
				<th data-resizable-column-id="Компания">Компания</th>
                
				<th data-resizable-column-id="Аккаунт">Аккаунт</th>
            </tr>
			<tr>	
            {% for c in content %}
                
					<div class="mt-6 flex justify-content-between">
                        
						<td><p class="py-2 px-2 w-full {% cycle 'bg-gray-100' '' %}">{{ c.name }}</a></p></td>
                        <td><p class="py-2 px-2 w-full {% cycle 'bg-gray-100' '' %}">{{ c.type_worker }}</a></p></td>
						<td><p class="py-2 px-2 w-full {% cycle 'bg-gray-100' '' %}">{{ c.phone_number }}</a></p></td>
						<td><p class="py-2 px-2 w-full {% cycle 'bg-gray-100' '' %}">{{ c.company }}</a></p></td>
                        
						<td><p class="py-2 px-2 w-full {% cycle 'bg-gray-100' '' %}">{{ c.user }}</a></p></td>
					</div>
			</tr>
				{% endfor %}
		</table>

    </ul>

{% endblock  %}



{% comment %} {% block footer %}
<footer class="py-4 bg-dark">
    <div class="container">
        <p class="m-0 text-center text-white">Copyright &copy; Аварийно-диспечерская служба 2024</p>
    </div>
</footer>
{% endblock  %} {% endcomment %}

handbook/templates/handbook/handbook.html
{% extends "base.html" %}

{%load static %}

{% block css %}
    <link rel="stylesheet" href="{% static "deps/css/my_footer_css.css" %}">
	
{% endblock  %}

{% block content %}

<div class="container-fluid">
<div class="guides-content">
    <div class="row">
        <div class="col-md-2">
            <h4 class="text-center">Справочники</h4>
            <ul class="nav nav-pills  col-md-12">
                
                <li class=" col-md-12">
                    <a href="{% url "company:company" %}">Управляющие компании</a>
                </li>
                <li class=" col-md-12">
                    <a href="{% url "handbook:city" %}">Города</a>
                </li>
                <li class=" col-md-12">
                    <a href="{% url "handbook:street" %}">Улицы</a>
                </li>
                <li class=" col-md-12">
                    <a href="{% url "handbook:house" %}">Дома</a>
                </li>
                <li class=" col-md-12">
                    <a href="{% url "handbook:type_application" %}">Тип заявки</a>
                </li>
                <li class=" col-md-12">
                    <a href="{% url "handbook:view_application" %}">Вид заявки</a>
                </li>
                <li class=" col-md-12">
                    <a href="{% url "handbook:status_application" %}">Статус заявки</a>
                </li>
                <li class=" col-md-12">
                    <a href="{% url "handbook:executor" %}">Исполнители</a>
                </li>
                <li class=" col-md-12">
                    <a href="{% url "handbook:master" %}">Мастера</a>
                </li>
                


{% endblock  %}


{% block footer %}
<footer class="py-4 bg-dark">
    <div class="container">
        <p class="m-0 text-center text-white">Copyright &copy; Аварийно-диспечерская служба 2024</p>
    </div>
</footer>
{% endblock  %} 

handbook/templates/handbook/master.html
{% extends "handbook/handbook.html" %}
{%load static %}

{% block css %}
    <link rel="stylesheet" href="{% static "deps/css/my_footer_css.css" %}">
	<link rel="stylesheet" href="{% static "deps/css/table.css" %}">
{% endblock  %}

{% block content %}
{% csrf_token %}
<h5 class="m-2"><strong>{{ title }}</strong></h5>
	<ul>
		<table class="table table-bordered" data-resizable-columns-id="demo-table">
			<tr>
				<th data-resizable-column-id="Имя">Имя</th>
				<th data-resizable-column-id="Телефон">Телефон</th>
				<th data-resizable-column-id="Компания">Компания</th>
				<th data-resizable-column-id="Исполнители">Исполнители</th>
                <th data-resizable-column-id="Аккаунт пользователя">Аккаунт пользователя</th>
			</tr>
			<tr>	
            {% for c in content %}
                
					<div class="mt-6 flex justify-content-between">
                        
						<td><p class="py-2 px-2 w-full {% cycle 'bg-gray-100' '' %}">{{ c.name }}</a></p></td>
						<td><p class="py-2 px-2 w-full {% cycle 'bg-gray-100' '' %}">{{ c.phone_number }}</a></p></td>
						<td><p class="py-2 px-2 w-full {% cycle 'bg-gray-100' '' %}">{{ c.company }}</a></p></td>
						{% comment %} <td><p class="py-2 px-2 w-full {% cycle 'bg-gray-100' '' %}">{{ c.workers.all }}</a></p></td> {% endcomment %}
						
						<td>{% for worker in c.workers.all %}
							
							<p class="py-2 px-2 w-full {% cycle 'bg-gray-100' '' %}">{{ worker }}</a></p>{% endfor %}
							
						</td>
						<td><p class="py-2 px-2 w-full {% cycle 'bg-gray-100' '' %}">{{ c.user }}</a></p></td>
                    </div>
			</tr>
				{% endfor %}
		</table>

    </ul>
{% endblock  %}

handbook/templates/handbook/master_add.html
{% extends "base.html" %}

{%load static %}
{% load bootstrap4 %}
{% block css %}


<link rel="stylesheet" href="{% static "deps/css/my_footer_css.css" %}">
<link rel="stylesheet" href="{% static "deps/css/form.css" %}">
{% endblock  %}


{% block content %}

    <div class="offset-5 col-md-6">
    <h1>Добавить мастера</h1>
    </div>
    <div>
        <form method="post" enctype='multipart/form-data' id="worker-form">
        
            {% csrf_token %}
            {% bootstrap_form form %}
            {% buttons %}
            <button type="submit" class="btn btn-primary"> Сохранить </button>
            {% endbuttons %}
            </form>
            <div class="posts"></div>
            
            
            
            {% endblock  %}

handbook/templates/handbook/street.html
{% extends "handbook/handbook.html" %}
{%load static %}

{% block css %}
    <link rel="stylesheet" href="{% static "deps/css/my_footer_css.css" %}">
	<link rel="stylesheet" href="{% static "deps/css/table.css" %}">
{% endblock  %}

{% block content %}
<li><a class="dropdown-item text-black" href="{% url "handbook:create_street" %}">Новая улица</a></li>
{% csrf_token %}
<h5 class="m-2"><strong>{{ title }}</strong></h5>
	<ul>
		<table class="table table-bordered" data-resizable-columns-id="demo-table">
			<tr>
				<th data-resizable-column-id="Название">Название</th>
                <th data-resizable-column-id="Город">Город</th>
				<th data-resizable-column-id="Действия">Действия</th>
            </tr>
			<tr>	
            {% for c in content %}
                
					<div class="mt-6 flex justify-content-between">
                        
						<td><p class="py-2 px-2 w-full {% cycle 'bg-gray-100' '' %}">{{ c.name }}</a></p></td>
                        <td><p class="py-2 px-2 w-full {% cycle 'bg-gray-100' '' %}">{{ c.city }}</a></p></td>
						<td><p class="py-2 px-2 w-full {% cycle 'bg-gray-100' '' %}">{{ c.do }}</a></p></td>
					</div>
			</tr>
				{% endfor %}
		</table>

    </ul>

{% endblock  %}



{% comment %} {% block footer %}
<footer class="py-4 bg-dark">
    <div class="container">
        <p class="m-0 text-center text-white">Copyright &copy; Аварийно-диспечерская служба 2024</p>
    </div>
</footer>
{% endblock  %} {% endcomment %}