ADS/urls.py
from django.contrib import admin
from django.urls import include, path, re_path

from list_of_request.views import page_not_found
from ATS.views import CallViewSet
from rest_framework.routers import DefaultRouter


router = DefaultRouter()
router.register(r'calls', CallViewSet)
from django.conf import settings
from django.conf.urls.static import static




urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main.urls', namespace='main')),
    path('list_of_request/', include('list_of_request.urls', namespace='list_of_request')),
    path('user/', include('users.urls', namespace='users')),
    path('handbook/', include('handbook.urls', namespace='handbook')),
    path('company/', include('companies.urls', namespace='company')),
    path('calls/', include('ATS.urls', namespace='ATS')),
    path('api/v1/drf-auth/', include('rest_framework.urls')),
    path('sms/', include('sms_app.urls', namespace='sms')),
    path('api/v1/auth/', include('djoser.urls')),
    # path('bot/', include('bot.urls')),
    re_path(r'^auth/', include('djoser.urls.authtoken')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
urlpatterns += router.urls


handler404 = page_not_found

users/urls.py
from django.urls import path
from .views import LoginFormView, RegistrationFormView, \
    LogoutFormView, UserProfileTemplateView, UserProfileFormView, UserVerifyView, \
    UserPasswordRecoveryFormView, UserSetPasswordFormView, MenuSectionsAdd, my_profile, \
    change_username

app_name = 'users'

urlpatterns = [
    path('login/', LoginFormView.as_view(), name='login'),
    path('register/', RegistrationFormView.as_view(), name='register'),
    path('profile/', UserProfileFormView.as_view(), name='myprofile'),
    
    path('change-username/', change_username, name='change-username'),
    path('my_profile/', my_profile, name='my_profile'),
    path('user_menu/', MenuSectionsAdd.as_view()),
    path('<int:id>/', UserProfileTemplateView.as_view(), name='profile'),
    path('logout/', LogoutFormView.as_view(), name='logout'),
    path('verify/<str:username>/<str:activation_key>/',
        UserVerifyView.as_view(), name='verify'),
    path('password-recovery/', UserPasswordRecoveryFormView.as_view(),
        name='password-recovery'),
    path('password-recovery-link/<str:email>/<str:password_recovery_key>/',
        UserSetPasswordFormView.as_view(), name='password-recovery-link'),
]

users/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser


from datetime import datetime
from dateutil.parser import parse as du_parse
from dateutil.relativedelta import relativedelta
from hashlib import sha1
from random import random

from django.dispatch import receiver
from django.db.models.signals import post_save
from django.conf import settings
from django.urls import reverse
from django.utils import timezone

from utils.sender import send_email


class User(AbstractUser):
    first_name = models.CharField(max_length=150, verbose_name='Имя')
    last_name = models.CharField( max_length=150, verbose_name='Фамилия')
    patronymic = models.CharField(max_length=150, blank=True, verbose_name="Отчество")
    is_admin = models.BooleanField(default=False, verbose_name='Администратор')
    is_executor = models.BooleanField(default=False, verbose_name='Исполнитель')
    is_dispatcher = models.BooleanField(default=False, verbose_name='Диспетчер')
    is_master = models.BooleanField(default=False, verbose_name='Мастер')
    is_duty_executor = models.BooleanField(default=False, verbose_name='Дежурный исполнитель')
    is_duty_dispatcher = models.BooleanField(default=False, verbose_name='Дежурный диспетчер')
    sections = models.ManyToManyField('MenuSections', verbose_name='Секции, разрешенные к показу', blank=True)
    job = models.CharField(max_length=150, verbose_name='Работа', blank=True)
    cookie_acceptance = models.BooleanField(default=False, verbose_name='Согласие использования файлов cookie')

    date_joined = last_login = None
    

    def __str__(self):
        return self.username
    
# class MenuSections(models.Model):
#     name = models.CharField(max_length=128,
#                             unique=True,
#                             verbose_name='Название')

#     def __str__(self):
#         return self.name

#     class Meta:
#         verbose_name = 'Секция меню в шапке пользователя'
#         verbose_name_plural = 'Секции меню в шапке пользователя'


class Profile(models.Model):
    MALE = "M"
    FEMALE = "F"
    UNKNOWN = "U"

    GENDERS = (
        (MALE, "Мужской"),
        (FEMALE, "Женский"),
        (UNKNOWN, "Не указан"),
    )

    user = models.OneToOneField(
        User, on_delete=models.CASCADE, verbose_name="Пользователь"
    )

    gender = models.CharField(
        max_length=1, choices=GENDERS, default=UNKNOWN, verbose_name="Пол"
    )
    birthday_at = models.DateField(null=True, blank=True, verbose_name="Дата рождения")
    avatar = models.ImageField(
        upload_to="avatars", blank=True, null=True, verbose_name="Аватар"
    )
    activation_key = models.CharField(
        max_length=128, blank=True, verbose_name="Ключ активации"
    )
    activation_key_expires = models.DateTimeField(
        blank=True, null=True, verbose_name="Ключ активации годен до"
    )
    password_recovery_key = models.CharField(
        max_length=128, blank=True, verbose_name="Ключ восстановления пароля"
    )
    password_recovery_key_expires = models.DateTimeField(
        blank=True, null=True, verbose_name="Ключ восстановления пароля годен до"
    )

    def __str__(self):
        return f"{self.user.username}'s profile"

    @receiver(post_save, sender=User)
    def create_profile(sender, instance, created, **kwargs):
        # если вызов произошел из loaddata, то пропускаем
        if kwargs.get("raw", False):
            return

        migration_in_progress = sender._meta.object_name == "Migrate"
        if not migration_in_progress and created:
            Profile.objects.create(user=instance).save()

    def deactivate_user(self):
        self.user.is_active = False
        self.user.save()

    def activate_user(self):
        self.user.is_active = True
        self.user.save()

    def generate_activation_key(self):
        self.activation_key = sha1(str(random()).encode("utf8")).hexdigest()
        self.activation_key_expires = timezone.now() + timezone.timedelta(hours=48)
        self.save()

    def is_activation_key_expired(self):
        if timezone.now() < self.activation_key_expires:
            return False
        return True

    def send_verify_mail(self):
        pass
        # verify_link = reverse(
        #     "users:verify", args=[self.user.username, self.activation_key]
        # )
        # subject = "Активация аккаунта"
        # message = (
        #     f"Чтобы активировать аккаунт, перейдите по ссылке: "
        #     f"{settings.BASE_URL}{verify_link}"
        # )

        # return send_email(self.user.email, False) #subject, message

    def verify(self, username: str, activation_key: str) -> bool:
        if (
            self.user.username == username
            and self.activation_key == activation_key
            and not self.is_activation_key_expired()
        ):
            self.activate_user()
            self.activation_key = ""
            self.activation_key_expires = None
            self.save()
            self.save()
            return True
        return False

    def generate_password_recovery_key(self):
        self.password_recovery_key = sha1(str(random()).encode("utf8")).hexdigest()
        self.password_recovery_key_expires = timezone.now() + timezone.timedelta(
            hours=48
        )
        self.save()

    def is_password_recovery_key_expired(self):
        if timezone.now() < self.password_recovery_key_expires:
            return False
        return True

    def send_password_recovery_mail(self):
        recovery_link = reverse(
            "users:password-recovery-link",
            args=[self.user.email, self.password_recovery_key],
        )
        subject = "Восстановление пароля"
        message = (
            f"Ваш логин: {self.user.username} \n"
            f"Для восстановления пароля, перейдите по ссылке: "
            f"{settings.BASE_URL}{recovery_link}"
        )

        return send_email(self.user.email, subject, False, message)

    def recovery_valid(self, email: str, key: str):
        if (
            self.user.email == email
            and self.password_recovery_key == key
            and not self.is_password_recovery_key_expired()
        ):
            return True
        return False


    def get_user_age(self):

        try:
            birth = du_parse(str(self.birthday_at), dayfirst = True)
            today_date = du_parse(str(datetime.today()), dayfirst = True)
            delta = relativedelta(today_date, birth)

            return delta.years
        except:
            return 'дата рождения не указана'

    class Meta:
        verbose_name = "Профиль"
        verbose_name_plural = "Профили"


'''Модель для хранения избранных заявок'''
class Favourite(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    favourites = models.ManyToManyField("list_of_request.Articles", blank=True)


class MenuSections(models.Model):
    name = models.CharField(max_length=128,
                            unique=True,
                            verbose_name='Название')

    def __str__(self):
        return self.name

    class Meta:
        verbose_name = 'Секция меню в шапке пользователя'
        verbose_name_plural = 'Секции меню в шапке пользователя'

users/forms/password_change_form.py
from django.contrib.auth.forms import PasswordChangeForm
from django import forms

class MyPasswordChangeForm(PasswordChangeForm):
    old_password = forms.CharField(widget=forms.PasswordInput(attrs={'placeholder': 'Старый пароль'}))
    new_password1 = forms.CharField(widget=forms.PasswordInput(attrs={'placeholder': 'Новый пароль'}))
    new_password2 = forms.CharField(widget=forms.PasswordInput(attrs={'placeholder': 'Подтверждение нового пароля'}))

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for field_name, field in self.fields.items():
            field.widget.attrs['class'] = 'form-control py-2 text-grey'

users/forms/profile_model_form.py
from django import forms
from users.models import User, Profile

GENDER_CHOICES = (
    ('M', 'Мужской'),
    ('F', 'Женский'),
)


class ProfileModelForm(forms.ModelForm):

    gender = forms.ChoiceField(
        choices=GENDER_CHOICES,
        label='Пол',
        widget=forms.RadioSelect()
    )
    birthday_at = forms.DateField(
        widget=forms.DateInput(attrs={'type': 'date', 'placeholder': 'Введите дату рождения'}),
        label='Дата рождения'
    )
    image = forms.ImageField(
        widget=forms.FileInput(),
        label='Аватар',
        required=False,
    )

    class Meta:
        model = User
        fields = ('gender', 'birthday_at', 'image')

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for field_name, field in self.fields.items():
            if field_name not in ('image', 'gender'):
                field.widget.attrs['class'] = 'form-control py-2 text-grey h-auto'
            elif field_name in ('image',):
                field.widget.attrs['class'] = 'form-control text-grey h-auto'
            else:
                field.widget.attrs['class'] = 'm-0 p-0 text-grey'

    def validate_avatar_size(self):
        max_file_size = 1048576
        image = self.cleaned_data.get('image')

        if not image:
            return None, None

        if image.size > max_file_size:
            return image, 'Ошибка! Максимальный размер загружаемого файла - 1 МБ.'

        return image, None

users/forms/user_login_form.py
from django import forms
from django.contrib.auth.forms import AuthenticationForm
from users.models import User


class UserLoginForm(AuthenticationForm):
    username = forms.CharField(widget=forms.TextInput(attrs={
        'placeholder': 'Введите имя пользователя',
    }))
    password = forms.CharField(widget=forms.PasswordInput(attrs={
        'placeholder': 'Введите пароль',
    }))

    class Meta:
        model = User
        fields = ('username', 'password')

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for field_name, field in self.fields.items():
            field.widget.attrs['class'] = 'form-control py-2'

users/forms/user_model_form.py
from django import forms
from users.models import User


class UserModelForm(forms.ModelForm):
    first_name = forms.CharField(
        widget=forms.TextInput(attrs={'placeholder': 'Введите имя'}),
        label='Имя',
    )
    patronymic = forms.CharField(
        widget=forms.TextInput(attrs={'placeholder': 'Введите Отчество'}),
        label='Отчество'
    )
    last_name = forms.CharField(
        widget=forms.TextInput(attrs={'placeholder': 'Введите Фамилию'}),
        label='Фамилия'
    )
    job = forms.CharField(
        widget=forms.TextInput(attrs={'placeholder': 'Введите професию'}),
        label='Профессия',
        required=False,
    )

    class Meta:
        model = User
        fields = ('first_name', 'patronymic', 'last_name', 'job')

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for field_name, field in self.fields.items():
            field.widget.attrs['class'] = 'form-control py-2 text-grey h-auto'

users/forms/user_password_recovery_form.py
from django import forms
from users.models import User


class UserPasswordRecoveryForm(forms.Form):
    email = forms.CharField(
        widget=forms.EmailInput(attrs={'placeholder': 'Введите адрес электронной почты'}),
        label='E-mail'
    )

    class Meta:
        model = User
        fields = ('email',)

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for field_name, field in self.fields.items():
            field.widget.attrs['class'] = 'form-control py-2'

users/forms/user_registration_form.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from users.models import User

GENDER_CHOICES = (
    ('M', 'Мужской'),
    ('F', 'Женский'),
)


class UserRegistrationForm(UserCreationForm):

    username = forms.CharField(
        widget=forms.TextInput(attrs={'placeholder': 'Введите имя пользователя'}),
        label='Имя пользователя'
    )
    email = forms.CharField(
        widget=forms.EmailInput(attrs={'placeholder': 'Введите адрес электронной почты'}),
        label='Адрес эл. почты'
    )
    password1 = forms.CharField(
        widget=forms.PasswordInput(attrs={'placeholder': 'Придумайте пароль'}),
        label='Пароль'
    )
    password2 = forms.CharField(
        widget=forms.PasswordInput(attrs={'placeholder': 'Подтвердите пароль'}),
        label='Подтверждение пароля'
    )
    first_name = forms.CharField(
        widget=forms.TextInput(attrs={'placeholder': 'Введите имя пользователя'}),
        label='Имя пользователя'
    )
    last_name = forms.CharField(
        widget=forms.TextInput(attrs={'placeholder': 'Введите фамилию пользователя'}),
        label='Имя пользователя'
    )
    patronymic = forms.CharField(
        widget=forms.TextInput(attrs={'placeholder': 'Введите отчество пользователя'}),
        label='Отчество',
        required=False
    )
    gender = forms.ChoiceField(
        choices=GENDER_CHOICES,
        label='Пол',
        widget=forms.RadioSelect(attrs={'class': 'custom-class'})
    )
    birthday_at = forms.DateField(
        widget=forms.DateInput(attrs={'type': 'date'}),
        label='Дата рождения'
    )
    image = forms.ImageField(
        widget=forms.FileInput(),
        label='Аватар',
        required=False
    )

    class Meta:
        model = User
        fields = ('username', 'email', 'password1', 'password2', 'first_name', 'patronymic', 'last_name')

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for field_name, field in self.fields.items():
            if field_name not in ('image', 'gender'):
                field.widget.attrs['class'] = 'form-control py-2 text-grey'
            elif field_name in ('image',):
                field.widget.attrs['class'] = 'form-control text-grey'
            else:
                field.widget.attrs['class'] = 'm-0 p-0 text-grey'

    def validate_avatar_size(self):
        max_file_size = 1048576
        image = self.cleaned_data.get('image')

        if not image:
            return None, None

        if image.size > max_file_size:
            return image, 'Ошибка! Максимальный размер загружаемого файла - 1 МБ.'

        return image, None

users/forms/user_set_password_form.py
from django import forms
from django.contrib.auth.forms import SetPasswordForm
from users.models import User


class UserSetPasswordForm(SetPasswordForm):
    new_password1 = forms.CharField(
        widget=forms.PasswordInput(attrs={'placeholder': 'Придумайте пароль'}),
        label='Пароль'
    )
    new_password2 = forms.CharField(
        widget=forms.PasswordInput(attrs={'placeholder': 'Подтвердите пароль'}),
        label='Повторить пароль'
    )

    class Meta:
        model = User
        fields = ('new_password1', 'new_password2')

    def __init__(self, user, *args, **kwargs):
        super().__init__(user, *args, **kwargs)
        for field_name, field in self.fields.items():
            field.widget.attrs['class'] = 'form-control py-2'

users/templates/users/login.html
{% extends "base.html" %}
{% comment %} {% load crispy_forms_tags %} {% endcomment %}



{% block content %}
<h1>
Вход в систему
</h1>
<form method="post">
    {% csrf_token %}
    {{form}}
    <p><button type="submit">Войти</button></p>
</form>
{% endblock %}

users/templates/users/profile_header.html
{% extends "base.html" %}
{% load static %}
{% load cache %}


{% block content %}
<div class="row">
    <div class="container mt-5">
        <div class="row">
            <!-- Профиль с данными пользователя -->
            <div class="col-md-5">
                <div class=" bg-white p-4 mb-4 mx-2 rounded custom-shadow">
                    <h3 class="text-center mb-4">Профиль пользователя</h3>
                    <form action="#" method="post" enctype="multipart/form-data">
                        {% csrf_token %}
                        <div class="row">
                            <div class="col-md-12 mb-3 text-center">
                                {% if user.image %}
                                    <img src="{{ user.image.url }}"
                                        alt="Аватар пользователя" class="img-fluid rounded-circle"
                                        style="max-width: 150px;">
                                {% else %}
                                    <img src="{% static "deps/images/baseavatar.jpg" %}"
                                        alt="Аватар пользователя" class="img-fluid rounded-circle"
                                        style="max-width: 150px;">
                                {% endif %}
                                <input type="file" class="form-control mt-3" id="id_image"
                                    name='image'
                                    accept="image/*">
                                    {% if form.image.errors %}
                                    <div class="alert alert-danger alert-dismissible fade show">{{form.image.errors}}</div>
                                    {% endif %}
                            </div>
                            <div class="col-md-12 mb-3">
                                <label for="id_first_name" class="form-label">Имя*</label>
                                <input type="text" class="form-control" id="id_first_name"
                                    name="first_name"
                                    placeholder="Введите ваше имя"
                                    value="{{ form.first_name.value }}"
                                    required>
                                    {% if form.first_name.errors %}
                                    <div class="alert alert-danger alert-dismissible fade show">{{form.first_name.errors}}</div>
                                    {% endif %}
                            </div>
                            <div class="col-md-12 mb-3">
                                <label for="id_last_name" class="form-label">Фамилия*</label>
                                <input type="text" class="form-control" id="id_last_name"
                                    name="last_name"
                                    placeholder="Введите вашу фамилию"
                                    value="{{ form.last_name.value }}"
                                    required>
                                    {% if form.last_name.errors %}
                                    <div class="alert alert-danger alert-dismissible fade show">{{form.last_name.errors}}</div>
                                    {% endif %}
                            </div>
                            <div class="col-md-12 mb-3">
                                <label for="id_username" class="form-label">Имя пользователя*</label>
                                <input type="text" class="form-control" id="id_username"
                                    name="username"
                                    placeholder="Введите ваше имя пользователя"
                                    value="{{ form.username.value }}"
                                    required>
                                    {% if form.username.errors %}
                                    <div class="alert alert-danger alert-dismissible fade show">{{form.username.errors}}</div>
                                    {% endif %}
                            </div>
                            <div class="col-md-12 mb-3">
                                <label for="id_email" class="form-label">Email*</label>
                                <input type="email" class="form-control" id="id_email"
                                    name="email"
                                    placeholder="Введите ваш email *youremail@example.com"
                                    value="{{ form.email.value }}"
                                    required>
                                    {% if form.email.errors %}
                                    <div class="alert alert-danger alert-dismissible fade show">{{form.email.errors}}</div>
                                    {% endif %}
                            </div>
                        </div>
                        <button type="submit" class="btn btn-dark">Сохранить</button>
                    </form>
                </div>
            </div>
            <!-- Корзина -->
            {% comment %} {% user_carts request as carts %} {% endcomment %}

            <div class="col-md-7">
                <div class=" bg-white p-4 mb-4 mx-2 rounded custom-shadow">
                    <h3 class="text-center mb-4">Заявки</h3>
                    <div class="container" id="cart-items-container">
                        <!-- Разметка корзины -->
                        {% comment %} {% include "includes/list.html" %} {% endcomment %}
                        <!-- Закончилась разметка корзины -->
                    </div>
                </div>
            </div>
            <!-- Оформленные заказы -->
            {% comment %} {% cache 60 user_orders user.id %} {% endcomment %}
            <div class="col-md-12">
                <div class=" bg-white p-4 mb-4 mx-2 rounded custom-shadow">
                    <h3 class="text-center mb-4">Выполненные заявки</h3>
                    <!-- Разметка заказов -->
                    <div class="container">
                        <div class="accordion" id="accordionExample">
                            {% for order in orders %}
                            <div class="accordion-item">
                                <h2 class="accordion-header" id="heading{{ order.id }}">
                                    <button class="accordion-button {% if order != orders.0 %}collapsed{% endif %}" type="button" data-bs-toggle="collapse" data-bs-target="#collapse{{ order.id }}" aria-expanded="false" aria-controls="collapse{{ order.id }}">
                                        Заказ № {{ order.id }} - {{ order.created_timestamp }} | Статус: <strong class="mx-2">{{order.status}}</strong>
                                    </button>
                                </h2>
                                <div id="collapse{{ order.id }}" class="accordion-collapse collapse {% if order == orders.0 %}show{% endif %}" aria-labelledby="heading{{ order.id }}" data-bs-parent="#accordionExample">
                                    <div class="accordion-body">
                                        <table class="table table-dark table-hover">
                                            <thead>
                                                <tr>
                                                    <th>Товар</th>
                                                    <th>Количество</th>
                                                    <th>Цена</th>
                                                    <th>Общая стоимость</th>
                                                </tr>
                                            </thead>
                                            <tbody>
                                                {% for item in order.orderitem_set.all %}
                                                <tr>
                                                    <td><a class="text-white" href="{% url 'goods:product' item.product.slug %}">{{ item.product.name }}</a></td>
                                                    <td>{{ item.quantity }}</td>
                                                    <td>{{ item.price }}</td>
                                                    <td>{{ item.products_price }}</td>
                                                    
                                                </tr>
                                                {% endfor %}
                                            </tbody>
                                        </table>
                                    </div>
                                </div>
                            </div>
                            {% endfor %}
                        </div>
                    </div>

                    <!-- Закончилась разметка заказов -->
                </div>
            </div>
            {% comment %} {% endcache %} {% endcomment %}
        </div>
    </div>
</div>
{% endblock  %}

users/templates/users/register.html
{% extends 'base.html' %}
{% comment %} {% load crispy_forms_tags %} {% endcomment %}

{% block title %}Регистрация{% endblock title %}

{% block content %}

    <h1>Регистрация</h1>
    <form method="post"action=".">
        {% csrf_token %}
        {{ form }}
        <button class="py-4 px-8 bg-teal-500 text-white">Зарегистрироваться</button>
    </form>   
{% endblock  %}  