ADS/urls.py
from django.contrib import admin
from django.urls import include, path, re_path

from list_of_request.views import page_not_found
from ATS.views import CallViewSet
from rest_framework.routers import DefaultRouter


router = DefaultRouter()
router.register(r'calls', CallViewSet)
from django.conf import settings
from django.conf.urls.static import static




urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main.urls', namespace='main')),
    path('list_of_request/', include('list_of_request.urls', namespace='list_of_request')),
    path('user/', include('users.urls', namespace='users')),
    path('handbook/', include('handbook.urls', namespace='handbook')),
    path('company/', include('companies.urls', namespace='company')),
    path('calls/', include('ATS.urls', namespace='ATS')),
    path('api/v1/drf-auth/', include('rest_framework.urls')),
    path('sms/', include('sms_app.urls', namespace='sms')),
    path('api/v1/auth/', include('djoser.urls')),
    # path('bot/', include('bot.urls')),
    re_path(r'^auth/', include('djoser.urls.authtoken')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
urlpatterns += router.urls


handler404 = page_not_found

ATS/urls.py
from django.urls import path
from ATS.views import call_list

app_name = 'ATS'

urlpatterns = [
    path('', call_list, name='call_list'),
]

main/urls.py
from django.urls import path
from main import views


app_name = 'main'

urlpatterns = [
    path('', views.index, name='index'),
    path('about/', views.about, name='about'),
]

sms_app/urls.py
from django.urls import path, include
from rest_framework.views import APIView
from .views import send_sms


app_name = 'sms_app'


#  from .tasks import inform_executor

urlpatterns = [
    path('send-sms/', send_sms, name='send_sms'),
    
]

users/urls.py
from django.urls import path
from .views import LoginFormView, RegistrationFormView, \
    LogoutFormView, UserProfileTemplateView, UserProfileFormView, UserVerifyView, \
    UserPasswordRecoveryFormView, UserSetPasswordFormView, MenuSectionsAdd, my_profile, \
    change_username

app_name = 'users'

urlpatterns = [
    path('login/', LoginFormView.as_view(), name='login'),
    path('register/', RegistrationFormView.as_view(), name='register'),
    path('profile/', UserProfileFormView.as_view(), name='myprofile'),
    
    path('change-username/', change_username, name='change-username'),
    path('my_profile/', my_profile, name='my_profile'),
    path('user_menu/', MenuSectionsAdd.as_view()),
    path('<int:id>/', UserProfileTemplateView.as_view(), name='profile'),
    path('logout/', LogoutFormView.as_view(), name='logout'),
    path('verify/<str:username>/<str:activation_key>/',
        UserVerifyView.as_view(), name='verify'),
    path('password-recovery/', UserPasswordRecoveryFormView.as_view(),
        name='password-recovery'),
    path('password-recovery-link/<str:email>/<str:password_recovery_key>/',
        UserSetPasswordFormView.as_view(), name='password-recovery-link'),
]

templates/base.html
{%load static %}

<!DOCTYPE html>
<html lang="en">


<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="{% static "deps/css/bootstrap/bootstrap.min.css" %}">
    <link rel="stylesheet" href="{% static "deps/css/my_css.css" %}">
    
    <!-- Стиль footer-a для главной страницы -->
    {% block css %}
    
    {% endblock  %}
    <!-- Favicons for different platforms -->
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <link rel="apple-touch-icon" sizes="180x180" href="{% static "deps/favicon/apple-touch-icon.png" %}">
    <link rel="icon" type="image/png" sizes="32x32" href="{% static "deps/favicon/favicon-32x32.png" %}">
    <link rel="icon" type="image/png" sizes="16x16" href="{% static "deps/favicon/favicon-16x16.png" %}">
    <link rel="manifest" href="{% static "deps/favicon/site.webmanifest" %}">
    <title>{{ title }}</title>
</head>

<body>
    <header>
        <nav class="navbar navbar-expand-lg bg-dark" data-bs-theme="dark">
            <div class="container">
                <a class="navbar-brand" href="{% url "main:index" %}">АДС</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse"
                    data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent"
                    aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                
                <div class="collapse navbar-collapse" id="navbarSupportedContent">
                    <ul class="navbar-nav me-auto mb-2 mb-lg-0">
                        <li class="nav-item dropdown ">
                            <a class="nav-link dropdown-toggle text-white" href="#" role="button"
                                data-bs-toggle="dropdown" aria-expanded="false">
                                Информация
                            </a>
                            <ul class="dropdown-menu">
                                
                                <li><a class="dropdown-item  text-white" href="{% url "main:about" %}">Про нас</a></li>
                            </ul>
                        
                            {% if not user.is_authenticated %}
                                <li><a class="nav-link dropdown-toggle  text-white" href="{% url "users:login" %}">Войти</a>
                                </li>
                                <li><a class="nav-link dropdown-toggle  text-white" href="{% url "users:register" %}">Регистрация</a>
                                </li>
                            {% else %}
                                
                                <li class="nav-item dropdown ">
                                    <a class="nav-link dropdown-toggle text-white" href="#" role="button"
                                        data-bs-toggle="dropdown" aria-expanded="false">
                                        Профиль
                                    </a>
                                    <ul class="dropdown-menu">
                                        <li><a class="dropdown-item  text-white" href="{% url "users:my_profile" %}">Мой профиль</a>
                                        </li>
                                        {% if user.is_admin or user.is_staff %}
                                        <li><a class="dropdown-item  text-white" href="{% url "admin:index" %}">Админ панель</a></li>
                                        {% endif %}
                                        <li>
                                            <hr class="dropdown-divider">
                                        </li>
                                        
                            
                                    </ul>
                                    {% if user.is_authenticated %}
                                        <li><a class="py-2 px-2 rounded-xl btn btn-outline-success text-white" href="{% url "list_of_request:create_application" %}">+Новая заявка</a></li>
                                            <li class="nav-item dropdown">
                                                <a class="nav-link dropdown-toggle text-white" href="#" role="button"
                                                    data-bs-toggle="dropdown" aria-expanded="false">
                                                    Заявки🔻
                                                </a>
                                                <ul class="dropdown-menu">
                                                    <li><a class="nav-link dropdown-toggle text-white" href="{% url "list_of_request:applications" %}">Все заявки</a></li>    
                                                    <li><a class="nav-link dropdown-toggle text-white" href="{% url "list_of_request:new_applications" %}">Новые Заявки</a></li>
                                                    <li><a class="nav-link dropdown-toggle text-white" href="{% url "list_of_request:assigned_applications" %}">Назначенные заявки</a></li>
                                                    <li><a class="nav-link dropdown-toggle text-white" href="{% url "list_of_request:complete_applications" %}">Выполненные заявки</a></li>
                                                    <li><a class="nav-link dropdown-toggle text-white" href="{% url "list_of_request:search_application" %}">Поиск заявок</a></li>
                                                </ul>
                                            </li>
                                        <li><a class="nav-link dropdown-toggle text-white" href="{% url "ATS:call_list" %}">Звонки</a></li>
                                        <li><a class="nav-link dropdown-toggle text-white" href="{% url "handbook:handbook" %}">Справочник</a></li>
                                        {% comment %} <li><a class="nav-link dropdown-toggle text-white" href="{% url "sms:send_sms" %}">Отправить смс</a> {% endcomment %}
                                    {% endif %}
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse"
                    data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent"
                    aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span></li>{% endif %}
                </button>
                        </li>
                    </ul>
                    
                    {% comment %} <form class="d-flex" role="search">
                        <input class="form-control me-2" type="search" placeholder="Search" aria-label="Search">
                        <button class="btn btn-outline-success text-white" type="submit">Поиск</button>
                    </form> {% endcomment %}
                </div>
                <li class="nav-item dropdown">
                    {% if user.is_authenticated %}
                    <button class="btn btn-outline-danger" type="submit">
                        <a class="nav-link dropdown-toggle rounded-xl text-wrap" href="{% url "users:logout" %}">Выход</a></li></button>
                    {% endif %}
            </div>
        </nav>

        {% if messages %}
            <div class="py-6 px-6">
                {% for message in messages %}
                    <div class="py-4 px-4 bx-teal-300 text-white rounded-xl">
                        {{ message }}
                {% endfor %}
        {% endif %}
    </header>
    <section>
        
        <!-- Контент -->
        
            
                
                    <!-- Пустой блок на Ваше усмотрение -->
                </div>
                <div class="col-lg-10">
                    <!-- Контент на странице -->
                    {% include "includes/notifications.html" %}
                    {% block content %}
                    
                    {% endblock  %}
                </div>
            </div>
        </div>
    </section>
    {% block footer %}{% endblock %} 
    
    <script src="{% static "deps/js/jquery/jquery-3.7.0.min.js" %}"></script>
    {% comment %} <script src="{% static "deps/js/jquery-events.js" %}"></script> {% endcomment %}
    <script src="{% static "deps/js/jquery-ajax.js" %}"></script>
    <script src="{% static "deps/js/bootstrap/bootstrap.bundle.min.js" %}"></script>
</body>

</html>