ADS/urls.py
from django.contrib import admin
from django.urls import include, path, re_path

from list_of_request.views import page_not_found
from ATS.views import CallViewSet
from rest_framework.routers import DefaultRouter


router = DefaultRouter()
router.register(r'calls', CallViewSet)
from django.conf import settings
from django.conf.urls.static import static




urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main.urls', namespace='main')),
    path('list_of_request/', include('list_of_request.urls', namespace='list_of_request')),
    path('user/', include('users.urls', namespace='users')),
    path('handbook/', include('handbook.urls', namespace='handbook')),
    path('company/', include('companies.urls', namespace='company')),
    path('calls/', include('ATS.urls', namespace='ATS')),
    path('api/v1/drf-auth/', include('rest_framework.urls')),
    path('sms/', include('sms_app.urls', namespace='sms')),
    path('api/v1/auth/', include('djoser.urls')),
    # path('bot/', include('bot.urls')),
    re_path(r'^auth/', include('djoser.urls.authtoken')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
urlpatterns += router.urls


handler404 = page_not_found

list_of_request/urls.py
from django.urls import path, re_path, register_converter
from list_of_request import views
from rest_framework import routers
from . import converters

app_name = 'list_of_request'

register_converter(converters.FourDigitYearConverter, 'year4')

# router = routers.DefaultRouter()
# router.register(r'applications', views.ArticlesViewSet, basename='applications')
# print(router.urls)

urlpatterns = [
    path('', views.list_applications, name='applications'),
    path('new-application/', views.new_applications_list, name='new_applications'),
    path('<int:pk>/', views.ApplicationDetail.as_view(), name='application'),
    path('create/', views.create_application, name='create_application'),
    path('search/', views.ApplicationSearchList.as_view(), name='search_application'),
    path('<int:pk>/delete/', views.application_delete, name='delete_application'),
    path('<int:pk>/edit/', views.application_edit, name='edit_application'),
    path('<int:pk>/convert/', views.convert_to_complete_application, name='convert_application'),
    path('complete-applications/', views.complete_applications, name='complete_applications'),
    path('complete-applications/<int:pk>/', views.ApplicationCompleteDetail.as_view(), name='detail_complete_application'),
    path('assigned-applications/', views.assigned_applications, name='assigned_applications'),
    path('assigned-applications/<int:pk>/', views.ApplicationAssignDetail.as_view(), name='detail_assigned_applications'),
    # path('export-applications/', views.table_view, name='export_url'),
    # path('archive/<year4:year>/', views.archive, name='archive'),
    # path('api/v1/applications/', views.ArticlesAPIList.as_view()),
    # path('api/v1/applications/<int:pk>/', views.ArticlesAPIUpdate.as_view()),
    # path('api/v1/applicationsdelete/<int:pk>/', views.ArticlesAPIDestroy.as_view()),
    #path('api/v1/', include(router.urls))
    
    
]

list_of_request/models.py
from datetime import datetime
from django.db import models
from django.urls import reverse
from marshmallow import ValidationError
from numpy import insert
from phonenumber_field.modelfields import PhoneNumberField
from users.models import User
from django.utils.timezone import now
from django.utils.translation import gettext_lazy
import django_tables2 as tables


from companies.models import Companies, Master, Worker
from handbook.models import Dezh_Worker, House, Street, Type_application, View_application

# class CompleteApplication(models.Manager):
#     def get_queryset(self):
#         return super().get_queryset().filter(status=Articles.Status.NEW)
    
class Articles(models.Model):
        
    CURRENT = 'текущая'
    PLANNED = 'плановая'
    EMERGENCY = 'аварийная'
    DUTY = 'дежурная'
    COMMERCIAL = 'коммерческая'
    
    CHOICES_PRIORITY = (
        (CURRENT, 'текущая'),
        (PLANNED, 'плановая'),
        (EMERGENCY, 'аварийная'),
        (DUTY, 'дежурная'),
        (COMMERCIAL, 'коммерческая')
    )
    class Status(models.TextChoices):    
        NEW = "NEW", 'Новая'
        ASSIGNED = "ASSIGNED", 'Назначена'
        COMPLETED = "COMPLETED", 'Выполнена'
        CLOSED = "CLOSED", 'Закрыта'
        DELIVERED_TO_GP_TRSKK = "DELIVERED_TO_GP_TRSKK", 'Передано в ГП ЦРКК'    
        NO_POSSIBLE = "NO_POSSIBLE", "Нет возможности выполнения"
        FAILED = "FAILED", "Провалена"
        FOR_CONTRACTORS = "FOR_CONTRACTORS", 'Для подрядчиков'
        DELIVERED_IN_KRASKOM = "DELIVERED_IN_KRASKOM", 'Передано в Краском'
        DELIVERED_IN_RES = "DELIVERED_IN_RES", "Передано в РЭС"
        DELIVERED_IN_SB_RAS = "DELIVERED_IN_SB_RAS", 'Передано в СО РАН'
        DELIVERED_IN_PTO = "DELIVERED_IN_PTO", 'Передано в ПТО'

        
    
    
        
    priority = models.CharField(verbose_name='Приоритет заявки', max_length=12, choices=CHOICES_PRIORITY, default=CURRENT)
    create_time = models.DateTimeField(verbose_name='Дата создания заявки', default=datetime.now())
    street = models.ForeignKey(to=Street,  on_delete=models.PROTECT, null=True, blank=True, verbose_name="Улица")
    house = models.ForeignKey(to=House,  on_delete=models.PROTECT, null=True, blank=True, verbose_name="Дом",) 
    flat = models.CharField('Квартира', max_length=3, null=True)
    text = models.TextField('Текст заявки', null=True, blank=True)
    phone = PhoneNumberField('Номер телефона', null=True, blank=True, max_length=18)
    fio = models.CharField('ФИО заявителя', null=True, blank=True, max_length=255)
    job_date = models.DateField('Срок исполнения', null=True, blank=True)
    view = models.ForeignKey(to=View_application,  on_delete=models.PROTECT, verbose_name="Вид заявки", null=True, blank=True)
    type = models.ForeignKey(to=Type_application, on_delete=models.PROTECT, verbose_name="Тип заявки", null=True, blank=True)
    status = models.CharField('Статус заявки', max_length=50, choices=Status, default=Status.NEW)
    povtornaya = models.CharField("Повторная", max_length=50, null=True, blank=True, default=None)
    company = models.ForeignKey(to=Companies, on_delete=models.PROTECT, null=True, blank=True, verbose_name="Компания", default=None)
    master = models.ForeignKey(to=Master, null=True, blank=True, verbose_name="Мастер", on_delete=models.PROTECT)
    worker = models.ForeignKey(to=Worker, null=True, blank=True, verbose_name="Исполнитель", on_delete=models.PROTECT)
    dezh_worker = models.ForeignKey(to=Dezh_Worker, on_delete=models.PROTECT, null=True, blank=True, verbose_name="Дежурный исполнитель", default=None)
    comment = models.CharField('Комментарий', max_length=50, null=True, blank=True)
    call_record = models.FileField(upload_to='call_record', blank=True, null=True, verbose_name='Запись разговора')
    voice_record = models.FileField(upload_to='voice_message', blank=True, null=True, verbose_name='Голосовые сообщения')
    user = models.ForeignKey(User, on_delete=models.PROTECT, null=True, blank=True)
    new_sms = models.CharField('смс жителю "Заявка принята"', max_length=50, null=True, blank=True, default=None)
    sms_master = models.CharField('смс мастеру', max_length=50, null=True, blank=True, default=None)
    sms_about_worker = models.CharField('смс назначение исполнителя', max_length=50, null=True, blank=True, default=None)
    sms_worker = models.CharField('смс исполнителю', max_length=50, null=True, blank=True, default=None)
    sms_complete = models.CharField('смс выполнение заявки', max_length=50, null=True, blank=True, default=None)
    sms_dezh_worker = models.CharField('смс дежурному исполнителю', max_length=50, null=True, blank=True, default=None)
    materials = models.CharField('Материалы', max_length=50, null=True, blank=True)
    files = models.ImageField(upload_to='photo', blank=True, null=True, verbose_name="Прикрепленные файлы")
    last_update = models.DateTimeField(verbose_name='Дата изменения заявки', blank=True, null=True, auto_now=True)
    
    
    def save(self, *args, **kwargs):
        self.last_update = datetime.now()
        super().save(*args, **kwargs)
        
    def display_id(self):
        return f"{datetime.now().strftime('%y')}-{self.id:06d}"
        
            
    
    
    def get_absolute_url(self):
        return reverse('list_of_request:application', kwargs={"pk": self.pk})
    
    # def __str__(self):
    #     return self.text
    
    class Meta:
        db_table = 'applications'
        verbose_name = 'Заявку'
        verbose_name_plural = 'Заявки'
        ordering = ("id",)
        indexes = [
            models.Index(fields=["text"]),
        ]
        
    def __str__(self):
        return f"Заявка №{self.id} для {self.text}"


class ApplicationTable(tables.Table):
    '''
Таблица в которой выведены все заявки
''' 
    class PriorityColumn(tables.Column):
        def render(self, value):
            if value == 'аварийная':
                self.attrs = {"td": {"bgcolor": "FF3333"}}
            return value
    id=tables.LinkColumn("list_of_request:application", args=[tables.A("pk")])
    priority  = PriorityColumn()
    
    class Meta:
        model = Articles
        # add class="paleblue" to <table> tag
        attrs = {'class': 'paleblue'}
        

    


# class Application_complete(models.Model):
#     create_time = models.DateTimeField(verbose_name='Дата создания заявки', default=datetime.now())
#     street = models.ForeignKey(to=Street,  on_delete=models.PROTECT, null=True, blank=True, verbose_name="Улица")
#     house = models.ForeignKey(to=House,  on_delete=models.PROTECT, null=True, blank=True, verbose_name="Дом",) 
#     flat = models.CharField('Квартира', max_length=3, null=True)
#     text = models.TextField('Текст заявки', null=True, blank=True)
#     phone = PhoneNumberField('Номер телефона', null=True, blank=True, max_length=18)
#     fio = models.CharField('ФИО заявителя', null=True, blank=True, max_length=255)
#     job_date = models.DateField('Срок исполнения', null=True, blank=True)
#     view = models.ForeignKey(to=View_application,  on_delete=models.PROTECT, verbose_name="Вид заявки", null=True, blank=True)
#     type = models.ForeignKey(to=Type_application, on_delete=models.PROTECT, verbose_name="Тип заявки", null=True, blank=True)
#     status = models.CharField(verbose_name='Статус заявки', max_length=50)
#     povtornaya = models.CharField("Повторная", max_length=50, null=True, blank=True, default=None)
#     company = models.ForeignKey(to=Companies, on_delete=models.PROTECT, null=True, blank=True, verbose_name="Компания", default=None)
#     master = models.ForeignKey(to=Master, null=True, blank=True, verbose_name="Мастер", on_delete=models.PROTECT)
#     worker = models.ForeignKey(to=Worker, null=True, blank=True, verbose_name="Исполнитель", on_delete=models.PROTECT)
#     dezh_worker = models.ForeignKey(to=Dezh_Worker, on_delete=models.PROTECT, null=True, blank=True, verbose_name="Дежурный исполнитель", default=None)
#     comment = models.CharField('Комментарий', max_length=50, null=True, blank=True)
#     call_record = models.FileField(upload_to='call_record', blank=True, null=True, verbose_name='Запись разговора')
#     voice_record = models.FileField(upload_to='voice_message', blank=True, null=True, verbose_name='Голосовые сообщения')
#     user = models.ForeignKey(User, on_delete=models.PROTECT, null=True, blank=True)
#     new_sms = models.CharField('смс жителю "Заявка принята"', max_length=50, null=True, blank=True, default=None)
#     sms_master = models.CharField('смс мастеру', max_length=50, null=True, blank=True, default=None)
#     sms_about_worker = models.CharField('смс назначение исполнителя', max_length=50, null=True, blank=True, default=None)
#     sms_worker = models.CharField('смс исполнителю', max_length=50, null=True, blank=True, default=None)
#     sms_complete = models.CharField('смс выполнение заявки', max_length=50, null=True, blank=True, default=None)
#     sms_dezh_worker = models.CharField('смс дежурному исполнителю', max_length=50, null=True, blank=True, default=None)
#     materials = models.CharField('Материалы', max_length=50, null=True, blank=True)
#     files = models.ImageField(upload_to='photo', blank=True, null=True, verbose_name="Прикрепленные файлы")
#     last_update = models.DateTimeField(verbose_name='Дата изменения заявки', blank=True, null=True, auto_now=True)
#     converted_to_open = models.BooleanField(default=True)
    
#     class Meta:
#         db_table = 'application_complete'
#         verbose_name = 'Выполненную заявку'
#         verbose_name_plural = 'Выполненные заявки'
#         ordering = ("id",)
#         indexes = [
#             models.Index(fields=["text"]),
#         ]
    
#     def get_absolute_urll(self):
#         return reverse('list_of_request:detail_complete_application', kwargs={"pk": self.pk})
        
    
    
    
    
    
    
    
    

    
    

    
    
    
    
    
    
    
    

        

list_of_request/forms.py
from datetime import datetime

from django import forms

from .models import Articles

from django.core.validators import ValidationError


class ArticlesForm(forms.ModelForm):
    
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['street'].empty_label = 'Выберите улицу'
        self.fields['house'].empty_label = 'Выберите номер дома'
        self.fields['view'].empty_label = 'Выберите вид заявки'
        self.fields['type'].empty_label = 'Выберите тип заявки'
        self.fields['company'].empty_label = 'Выберите компанию'
        self.fields['master'].empty_label = 'Выберите мастера'
        self.fields['worker'].empty_label = 'Выберите исполнителя'
        
    class Meta:
        model = Articles
        fields = ['create_time', 'fio', 'phone', 'text', 'street', 'house', 'flat', 'materials', 'files', 'comment', 'view', 
                'type', 'company', 'master', 'worker', 'priority', 'status']
        

        widgets = {
            "priority": forms.Select(attrs={
                'class': 'form-control',
                'placeholder': 'Приоритет заявки'
            }),
            "status": forms.Select(attrs={
                'class': 'form-control',
                'placeholder': 'Статус заявки'
            }),
            "create_time": forms.DateTimeInput(attrs={
                'class': 'form-control'
            }),
            "fio": forms.TextInput(attrs={
                'class': 'form-control',
                'placeholder': 'ФИО', 
                }),
            "phone": forms.TextInput(attrs={
                'class': 'form-control',
                'placeholder': 'Телефон'
            }),
            "text": forms.Textarea(attrs={
                'class': 'form-control',
                'placeholder': 'Текст заявки'
                
            }),
            "street": forms.Select(attrs={
                'class': 'form-control',
                'placeholder': 'Улица'
            }),
            "house": forms.Select(attrs={
                'class': 'form-control'
            }),
            "flat": forms.TextInput(attrs={
                'class': 'form-control',
                'placeholder': 'Квартира'
            }),
            "materials": forms.TextInput(attrs={
                'class': 'form-control',
                'placeholder': 'Материалы'
            }),
            "files": forms.FileInput(attrs={
                'class': 'form-control'
            }),
            "comment": forms.TextInput(attrs={
                'class': 'form-control',
                'placeholder': 'Комментарий'
            }),
            "view": forms.Select(attrs={
                'class': 'form-control'
            }),
            "type": forms.Select(attrs={
                'class': 'form-control'
            }),
            "company": forms.Select(attrs={
                'class': 'form-control'
            }),
            "master": forms.Select(attrs={
                'class': 'form-control'
            }),
            "worker": forms.Select(attrs={
                'class': 'form-control'
            })
    }
        
    def clean(self):
        cleaned_data = super().clean()
        return cleaned_data
        
    # def clean_fio(self):
    #     fio = self.cleaned_data['fio']
    #     if not fio:
    #         raise forms.ValidationError('Поле "ФИО заявителя" не может быть пустым')
    #     return fio  
    
    # def clean_text(self):
    #     text = self.cleaned_data['text']
    #     if not text:
    #         raise forms.ValidationError('Поле "Текст заявки" не может быть пустым')
    #     return text
    
    # def clean_street(self):
    #     street = self.cleaned_data['street']
    #     if not street:
    #         raise forms.ValidationError('Поле "Улица" не может быть пустым')
    #     return street
    
    # def clean_house(self):
    #     house = self.cleaned_data['house']
    #     if not house:
    #         raise forms.ValidationError('Поле "Дом" не может быть пустым')
    #     return house
    
    # def clean_view(self):
    #     view = self.cleaned_data['view']
    #     if not view:
    #         raise forms.ValidationError('Поле "Вид заявки" не может быть пустым')
    #     return view 
        
    # def clean_type(self):
    #     type = self.cleaned_data['type']
    #     if not type:
    #         raise forms.ValidationError('Поле "Тип заявки" не может быть пустым')
    #     return type
    
        

list_of_request/templates/list_of_request/application_assign_detail.html
{% extends "base.html" %}
{% load bootstrap4 %}
{%load static %}
{% bootstrap_javascript jquery='full' %}
{% block css %}
    <link rel="stylesheet" href="{% static "deps/css/my_footer_css.css" %}">
	
    
{% endblock  %}

{% block content %}
<div class="offset-5 col-md-6">
    

    <table class="table table-bordered" data-resizable-columns-id="demo-table">
        
    <h3 class="mb-4 text-xl">{{ object.date }}</h3>
    <h2 class="mb-4 text-xl">{{ object.street }}</h2>
    <h3 class="mb-4 text-xl">{{ object.house }}</h3>
    <h3 class="mb-4 text-xl">{{ object.flat }}</h3>
    <h3 class="mb-4 text-xl">{{ object.fio }}</h3>
    <h3 class="mb-4 text-xl">{{ object.phone }}</h3>
    <h3 class="mb-4 text-xl">{{ object.text}}</h3>
    <h3 class="mb-4 text-xl">{{ object.materials }}</h3>
    <h3 class="mb-4 text-xl">{{ object.worker }}</h3>
    <h3 class="mb-4 text-xl">{{ object.user }}</h3>

    </table>
    <hr class="my-4">
    {% if user.is_admin or user.is_staff %}
    
    <a href="#" class="py-2 px-4 rounded-xl btn btn-outline-success">Изменить заявку</a>
    <a href="#" class="py-2 px-4 rounded-xl btn btn-outline-danger">Удалить заявку</a>
    <hr class="my-4">{% endif %}
<a href=" {% url "list_of_request:applications" %}" class="py-2 px-4 rounded-xl btn btn-outline-success">Вернуться к списку заявок</a>
    </div>  
</div>

{% endblock  %}


{% block footer %}
<footer class="py-4 bg-dark">
    <div class="container">
        <p class="m-0 text-center text-white">Copyright &copy; Аварийно-диспечерская служба 2024</p>
    </div>
</footer>
{% endblock  %} 

list_of_request/templates/list_of_request/application_detail.html
{% extends "base.html" %}
{% load bootstrap4 %}
{%load static %}
{% bootstrap_javascript jquery='full' %}
{% block css %}
    <link rel="stylesheet" href="{% static "deps/css/my_footer_css.css" %}">
	
    
{% endblock  %}

{% block content %}
<div class="offset-5 col-md-6">
    

    <table class="table table-bordered" data-resizable-columns-id="demo-table">
        
    <h3 class="mb-4 text-xl">{{ object.date }}</h3>
    <h2 class="mb-4 text-xl">{{ object.street }}</h2>
    <h3 class="mb-4 text-xl">{{ object.house }}</h3>
    <h3 class="mb-4 text-xl">{{ object.flat }}</h3>
    <h3 class="mb-4 text-xl">{{ object.fio }}</h3>
    <h3 class="mb-4 text-xl">{{ object.phone }}</h3>
    <h3 class="mb-4 text-xl">{{ object.text}}</h3>
    <h3 class="mb-4 text-xl">{{ object.materials }}</h3>
    <h3 class="mb-4 text-xl">{{ object.worker }}</h3>
    <h3 class="mb-4 text-xl">{{ object.user }}</h3>

    </table>

    </div>  
</div>

{% endblock  %}


{% block footer %}
<footer class="py-4 bg-dark">
    <div class="container">
        <p class="m-0 text-center text-white">Copyright &copy; Аварийно-диспечерская служба 2024</p>
    </div>
</footer>
{% endblock  %} 

list_of_request/templates/list_of_request/assigned_applications.html
{% extends "base.html" %}
{% block content %}
{% load bootstrap4 %}
<!--Разметка модального окна новой заявки-->
{% comment %} <button
    type="button"
    class="btn btn-dark btn-light"
    data-bs-toggle="modal"
    data-bs-target="#modalId"
>
    Создать новую заявку
</button>
<div class="modal fade" id="modalId" tabindex="-1" role="dialog" aria-labelledby="modalTitleId" aria-hidden="true">
    <div class="modal-dialog modal-dialog-scrollable">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="modalTitleId">
                    Новая заявка
                </h5>
                <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
            </div>
            <div class="modal-body">
                <div class="container-fa-align-center">
                    
                    {% include "list_of_request/create_application.html" %}
                        
                
                </div>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">
                    Закрыть
                </button>
                <a class="btn btn-dark" href="{% url "list_of_request:create_application" %}">
                    Сохранить
                </a>
                {% comment %} <button type="button" class="btn btn-primary">Сохранить</button> 
            </div>
        </div>
    </div>
</div> {% endcomment %}
<!--Закончилась разметка модального окна новой заявки-->
<div class='text-center py-4 px-2 bg-gray-200 font-semibold'>{{title}}</div>
<div class="table-responsive">
    <table class="table table-bordered" data-resizable-columns-id="demo-table">
    <tr>
        <th data-resizable-column-id="id">Номер</th>
        <th data-resizable-column-id="Статус заявки">Статус заявки</th>
        <th data-resizable-column-id="Дата">Дата создания</th>
        <th data-resizable-column-id="Улица">Улица</th>
        <th data-resizable-column-id="Дом">Дом</th>
        <th data-resizable-column-id="Квартира">Квартира</th>
        <th data-resizable-column-id="Текст заявки">Текст заявки</th>
        <th data-resizable-column-id="Срок исполнения">Срок исполнения</th>
        <th data-resizable-column-id="ФИО заявителя">ФИО заявителя</th>
        <th data-resizable-column-id="Телефон">Телефон</th>
        <th data-resizable-column-id="Вид заявки">Вид заявки</th>
        <th data-resizable-column-id="Тип заявки">Тип заявки</th>
        <th data-resizable-column-id="Комментарий">Комментарий</th>
        <th data-resizable-column-id="Повторная">Повторная</th>
        <th data-resizable-column-id="Приоритет заявки">Приоритет заявки</th>
        <th data-resizable-column-id="Управляющая компания">Управляющая компания</th>
        <th data-resizable-column-id="Исполнитель">Исполнитель</th>
        <th data-resizable-column-id="Мастер">Мастер</th>
        <th data-resizable-column-id="СМС исполнителю">СМС исполнителю</th>
        <th data-resizable-column-id="СМС мастеру">СМС мастеру</th>
        <th data-resizable-column-id="Материал">Материал</th>
        <th data-resizable-column-id="Автор">Автор</th>
        
    </tr>
    <tr>	
        
        {% for c in content %}
        
            <div class="mt-6 flex justify-content-between">
                <td><p class="py-2 px-2 w-full {% cycle 'bg-gray-100' '' %}"><a href={{c.get_absolute_url}}>{{ c.id }}</a></p></td>
                <td><p class="py-2 px-2 w-full {% cycle 'bg-gray-100' '' %}">{{ c.get_status_display }}</p></td>
                <td><p class="py-2 px-2 w-full {% cycle 'bg-gray-100' '' %}">{{ c.create_time }}</p></td>
                <td><p class="py-2 px-2 w-full {% cycle 'bg-gray-100' '' %}">{{ c.street }}</p></td>
                <td><p class="py-2 px-2 w-full {% cycle 'bg-gray-100' '' %}">{{ c.house }}</p></td>
                <td><p class="py-2 px-2 w-full {% cycle 'bg-gray-100' '' %}">{{ c.flat }}</p></td>
                <td><p class="py-2 px-2 w-full {% cycle 'bg-gray-100' '' %}">{{c.text|truncatechars:35}}</p></td>
                <td><p class="py-2 px-2 w-full {% cycle 'bg-gray-100' '' %}">{{ c.job_date }}</p></td>
                <td><p class="py-2 px-2 w-full {% cycle 'bg-gray-100' '' %}">{{ c.fio }}</p></td>
                <td><p class="py-2 px-2 w-full {% cycle 'bg-gray-100' '' %}">{{ c.phone }}</p></td>
                <td><p class="py-2 px-2 w-full {% cycle 'bg-gray-100' '' %}">{{ c.view }}</p></td>
                <td><p class="py-2 px-2 w-full {% cycle 'bg-gray-100' '' %}">{{ c.type }}</p></td>
                <td><p class="py-2 px-2 w-full {% cycle 'bg-gray-100' '' %}">{{ c.comment }}</p></td>
                <td><p class="py-2 px-2 w-full {% cycle 'bg-gray-100' '' %}">{{ c.povtornaya }}</p></td>
                <td><p class="py-2 px-2 w-full {% cycle 'bg-gray-100' '' %}">{{ c.get_priority_display }}</p></td>
                <td><p class="py-2 px-2 w-full {% cycle 'bg-gray-100' '' %}">{{ c.house.company }}</p></td>

                <td><p class="py-2 px-2 w-full {% cycle 'bg-gray-100' '' %}">{% for w in c.house.worker.all %}
                    <h6 class="mb-4 text-xl"> {{ w }} </h6>{% endfor %}</p></td>
                    
                <td><p class="py-2 px-2 w-full {% cycle 'bg-gray-100' '' %}">{{ c.house.master }}</p></td>
                <td><p class="py-2 px-2 w-full {% cycle 'bg-gray-100' '' %}">{{ c.sms_worker }}</p></td>
                <td><p class="py-2 px-2 w-full {% cycle 'bg-gray-100' '' %}">{{ c.sms_master }}</p></td>
                <td><p class="py-2 px-2 w-full {% cycle 'bg-gray-100' '' %}">{{ c.materials }}</p></td>
                <td><p class="py-2 px-2 w-full {% cycle 'bg-gray-100' '' %}">{{ c.user }} </p></td>
            </div>
    </tr>
    {% empty %}
        <p class="py-2 px-2 w-full">В базе данных еще нет заявок...</p>
        {% endfor %}
</table> 
</div>

<!-- Пагинация -->


<nav aria-label="Page navigation example">
    <ul class="pagination justify-content-center my-4">
        <div class="custom-shadow d-flex">
            <li class="page-item {% if not page_obj.has_previous %}disabled{% endif %}">
                <a class="page-link" href="{% if page_obj.has_previous %}
                ?page={{ page_obj.previous_page_number }}
                {% else %}
                #
                {% endif %}">Назад</a>
            </li>
            {% for page in page_obj.paginator.page_range %}
            {% if page >= page_obj.number|add:-2 and page <= page_obj.number|add:2 %}
            <li class="page-item {% if page_obj.number == page %}active{% endif %}">
                <a class="page-link" href="?page={{ page }}">{{ page }}</a>
            </li>
            {% endif %}
            {% endfor %}
            

            <li class="page-item {% if not page_obj.has_next %}disabled{% endif %}">
                <a class="page-link" href="{% if page_obj.has_next %}
                ?page={{ page_obj.next_page_number }}
                {% else %}
                #
                {% endif %}">Дальше</a>
            </li>
        </div>
    </ul>
</nav>

{% endblock  %}